--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BLAST1718/LELEL
build-by-default: true
branches:
- main
projects:
  LELEL:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.0.1
        branch: master
...
